baseurl = "https://mywebsite-5f0.pages.dev/"
theme = "hugo-coder"
title = "Aryan Mehesare"
languagecode = "en"
defaultContentLanguage = "en"
googleAnalytics = "G-BNDTXYTWR8"
paginate = 20

enableEmoji = true

enableGitInfo = true

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Aryan Mehesare"
  # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  # license = '<a rel="license" href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPL-3.0</a>'
  info = "Student and Tech Enthusiast"
  description = "Aryan Mehesare's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/logo.png"
  # gravatar = "john.doe@example.com"

  dateFormat = "January 2, 2006"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme = "auto"

  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle = false

  # Series see also post count
  maxSeeAlsoItems = 5

  # Git Commit in Footer, uncomment the line below to enable it
  commit = "https://github.com/mortal22soul/mywebsite/tree/"

  # Right To Left, shift content direction for languagues such as Arabic
  rtl = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:aryan22mehesare@proton.me"
  target = "_blank"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/mortal22soul/"
  target = "_blank"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 3
  url = "https://t.me/mortal22soul"
  target = "_blank"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/mortal22soul/"
  target = "_blank"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 6
  url = "https://myhugosite.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
  target = "_blank"
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 4
  url = "contact/"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = false